# Generated by Django 4.2.1 on 2023-05-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayjot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('user', 'date')},
        ),
    ]
