# Generated by Django 4.2.1 on 2023-05-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayjot_backend', '0002_alter_entry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='diary',
            field=models.TextField(blank=True),
        ),
    ]
